[tool.black]
line-length = 88
target-version = ['py313']
exclude = '''
(
    migrations
    | venv
    | manage.py
    | .git
    | __pycache__
    | .pyc
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
line_length = 88
