# Generated by Django 5.1.6 on 2025-02-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
