# Generated by Django 5.1.6 on 2025-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_remove_bookanalysis_intermediate_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50, unique=True)),
                ("model_name", models.CharField(max_length=5)),
            ],
        ),
    ]
