services:
  db:
    image: postgres:17.4
    env_file:
      - ../.env

  web:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    image: smartbook
    env_file:
      - ../.env
    volumes:
      - static_volume:/opt/smartbook/static
      - shm:/dev/shm
    depends_on:
      - db
    restart: always
    command: bash ./scripts/run-with-gunicorn.sh 2

  async:
    image: smartbook
    env_file:
      - ../.env
    volumes:
      - shm:/dev/shm
    depends_on:
      - web
    restart: always
    command: >
      bash -c "daphne -u /dev/shm/daphne.sock smartbook.asgi:application"


  proc:
    image: smartbook
    env_file:
      - ../.env
    depends_on:
      - web
    restart: always
    command: >
      bash -c "./manage.py run_analysis"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/smartbook/static
      - shm:/dev/shm
    depends_on:
      - web
      - async

volumes:
  static_volume:
  shm:
